name: xplugin
channels:
  - conda-forge

dependencies:
  # Build tools
  - cmake
  - cxx-compiler
  - ninja
  # testing
  - doctest
  # examples
  - nlohmann_json
  # docs
  - doxygen
  - sphinx
  - sphinx_rtd_theme
  - breathe
  - sphinx-sitemap
